# Generated by Django 6.1 on 2026-09-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_googleaccount_subscription_delete_goofle_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
