# Generated by Django 6.1 on 2026-09-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_billing_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('software', 'Software'), ('music', 'Music'), ('gaming', 'Gaming'), ('education', 'Education'), ('fitness', 'Fitness'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
