# Generated by Django 6.1 on 2026-09-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleaccount',
            name='google_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
