# Generated by Django 6.1 on 2026-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_googleaccount_google_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='gmail_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
