# Generated by Django 6.1 on 2026-09-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscription_google_account_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('google_account', 'gmail_message_id'), name='unique_google_message'),
        ),
    ]
