# Generated by Django 6.1 on 2026-09-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscription_unique_google_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='google_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.googleaccount'),
        ),
    ]
